// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getMangaBySlug = `-- name: GetMangaBySlug :one
SELECT m.slug, m.title, m.status, m.description, m.authors, m.genres, m.cover_url,
       d.id AS dict_id, d.state
FROM manga m
LEFT JOIN dictionary d ON d.slug = m.slug
WHERE m.slug = ?
`

type GetMangaBySlugRow struct {
	Slug        string
	Title       string
	Status      string
	Description string
	Authors     json.RawMessage
	Genres      json.RawMessage
	CoverUrl    string
	DictID      sql.NullString
	State       sql.NullString
}

func (q *Queries) GetMangaBySlug(ctx context.Context, slug string) (GetMangaBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getMangaBySlug, slug)
	var i GetMangaBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Description,
		&i.Authors,
		&i.Genres,
		&i.CoverUrl,
		&i.DictID,
		&i.State,
	)
	return i, err
}

const listManga = `-- name: ListManga :many
WITH filtered AS (
    SELECT d.id AS dict_id, d.slug, d.state,
           COALESCE(m.title, d.title) AS title,
           COALESCE(m.status, '') AS status,
           COALESCE(m.description, '') AS description,
           COALESCE(NULLIF(m.cover_url, ''), NULLIF(d.cover_url, ''), '') AS cover_url,
           COALESCE(m.authors, '[]') AS authors,
           COALESCE(m.genres, '[]') AS genres,
           COALESCE(m.synced_at, d.created_at) AS synced_at
    FROM dictionary d
    LEFT JOIN manga m ON m.slug = d.slug
    WHERE (? = '' OR d.title LIKE CONCAT('%', ?, '%'))
      AND (? = '' OR d.state = ?)
      AND (? = '' OR m.status = ?)
      AND (? = FALSE OR d.state != 'unavailable')
),
counted AS (SELECT COUNT(*) AS total FROM filtered),
langs AS (SELECT manga_id, JSON_ARRAYAGG(lang) AS langs FROM (SELECT DISTINCT manga_id, lang FROM chapters) t GROUP BY manga_id)
SELECT f.dict_id, f.slug, f.state, f.title, f.status, f.description,
       f.cover_url, f.authors, f.genres, f.synced_at,
       COALESCE(l.langs, '[]') AS languages,
       c.total
FROM filtered f, counted c
LEFT JOIN langs l ON l.manga_id = f.slug
ORDER BY CASE WHEN ? = 'last_update' THEN f.synced_at END DESC,
         CASE WHEN ? != 'last_update' THEN f.title END ASC
LIMIT ? OFFSET ?
`

type ListMangaParams struct {
	Column1 interface{}
	CONCAT  interface{}
	Column3 interface{}
	State   string
	Column5 interface{}
	Status  string
	Column7 interface{}
	Column8 interface{}
	Column9 interface{}
	Limit   int32
	Offset  int32
}

type ListMangaRow struct {
	DictID      string
	Slug        string
	State       string
	Title       string
	Status      string
	Description string
	CoverUrl    interface{}
	Authors     json.RawMessage
	Genres      json.RawMessage
	SyncedAt    time.Time
	Languages   json.RawMessage
	Total       int64
}

func (q *Queries) ListManga(ctx context.Context, arg ListMangaParams) ([]ListMangaRow, error) {
	rows, err := q.db.QueryContext(ctx, listManga,
		arg.Column1,
		arg.CONCAT,
		arg.Column3,
		arg.State,
		arg.Column5,
		arg.Status,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMangaRow
	for rows.Next() {
		var i ListMangaRow
		if err := rows.Scan(
			&i.DictID,
			&i.Slug,
			&i.State,
			&i.Title,
			&i.Status,
			&i.Description,
			&i.CoverUrl,
			&i.Authors,
			&i.Genres,
			&i.SyncedAt,
			&i.Languages,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertManga = `-- name: UpsertManga :exec

INSERT INTO manga (uuid, slug, title, description, status, authors, genres, cover_url, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    title=VALUES(title), description=VALUES(description),
    status=VALUES(status), authors=VALUES(authors), genres=VALUES(genres),
    cover_url=CASE WHEN VALUES(cover_url) != '' THEN VALUES(cover_url) ELSE cover_url END,
    synced_at=CURRENT_TIMESTAMP
`

type UpsertMangaParams struct {
	Uuid        string
	Slug        string
	Title       string
	Description string
	Status      string
	Authors     json.RawMessage
	Genres      json.RawMessage
	CoverUrl    string
}

// catalog.sql: manga table only (chapter data moved to chapters table)
func (q *Queries) UpsertManga(ctx context.Context, arg UpsertMangaParams) error {
	_, err := q.db.ExecContext(ctx, upsertManga,
		arg.Uuid,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Authors,
		arg.Genres,
		arg.CoverUrl,
	)
	return err
}
