// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getChapterPages = `-- name: GetChapterPages :many
SELECT s3_url FROM chapter_pages WHERE slug=? AND language=? AND chapter_num=? ORDER BY page_index
`

type GetChapterPagesParams struct {
	Slug       string
	Language   string
	ChapterNum string
}

func (q *Queries) GetChapterPages(ctx context.Context, arg GetChapterPagesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getChapterPages, arg.Slug, arg.Language, arg.ChapterNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var s3_url string
		if err := rows.Scan(&s3_url); err != nil {
			return nil, err
		}
		items = append(items, s3_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChaptersByLang = `-- name: GetChaptersByLang :many
SELECT slug, language, chapter_num, page_count, uploaded_at
FROM manga_chapters WHERE slug=? AND language=? AND uploaded=TRUE ORDER BY sort_key ASC
`

type GetChaptersByLangParams struct {
	Slug     string
	Language string
}

type GetChaptersByLangRow struct {
	Slug       string
	Language   string
	ChapterNum string
	PageCount  int32
	UploadedAt sql.NullTime
}

func (q *Queries) GetChaptersByLang(ctx context.Context, arg GetChaptersByLangParams) ([]GetChaptersByLangRow, error) {
	rows, err := q.db.QueryContext(ctx, getChaptersByLang, arg.Slug, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersByLangRow
	for rows.Next() {
		var i GetChaptersByLangRow
		if err := rows.Scan(
			&i.Slug,
			&i.Language,
			&i.ChapterNum,
			&i.PageCount,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChaptersBySlug = `-- name: GetChaptersBySlug :many
SELECT slug, language, chapter_num, page_count, uploaded, uploaded_at
FROM manga_chapters WHERE slug=? ORDER BY language, sort_key
`

type GetChaptersBySlugRow struct {
	Slug       string
	Language   string
	ChapterNum string
	PageCount  int32
	Uploaded   bool
	UploadedAt sql.NullTime
}

func (q *Queries) GetChaptersBySlug(ctx context.Context, slug string) ([]GetChaptersBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getChaptersBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersBySlugRow
	for rows.Next() {
		var i GetChaptersBySlugRow
		if err := rows.Scan(
			&i.Slug,
			&i.Language,
			&i.ChapterNum,
			&i.PageCount,
			&i.Uploaded,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMangaBySlug = `-- name: GetMangaBySlug :one
SELECT m.slug, m.title, m.status, m.description, m.authors, m.genres, m.cover_url,
       d.id AS dict_id, d.state
FROM manga m
LEFT JOIN dictionary d ON d.slug = m.slug
WHERE m.slug = ?
`

type GetMangaBySlugRow struct {
	Slug        string
	Title       string
	Status      string
	Description string
	Authors     json.RawMessage
	Genres      json.RawMessage
	CoverUrl    string
	DictID      sql.NullString
	State       sql.NullString
}

func (q *Queries) GetMangaBySlug(ctx context.Context, slug string) (GetMangaBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getMangaBySlug, slug)
	var i GetMangaBySlugRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Description,
		&i.Authors,
		&i.Genres,
		&i.CoverUrl,
		&i.DictID,
		&i.State,
	)
	return i, err
}

const getMangaLangsBySlug = `-- name: GetMangaLangsBySlug :many
SELECT language, available, downloaded FROM manga_langs WHERE slug=? ORDER BY language
`

type GetMangaLangsBySlugRow struct {
	Language   string
	Available  int32
	Downloaded int32
}

func (q *Queries) GetMangaLangsBySlug(ctx context.Context, slug string) ([]GetMangaLangsBySlugRow, error) {
	rows, err := q.db.QueryContext(ctx, getMangaLangsBySlug, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMangaLangsBySlugRow
	for rows.Next() {
		var i GetMangaLangsBySlugRow
		if err := rows.Scan(&i.Language, &i.Available, &i.Downloaded); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingChapters = `-- name: GetPendingChapters :many
SELECT mc.slug, mc.language, mc.chapter_num, COALESCE(d.id, '') AS dictionary_id
FROM manga_chapters mc
LEFT JOIN dictionary d ON d.slug = mc.slug
WHERE mc.uploaded=FALSE
ORDER BY mc.slug, mc.language, mc.sort_key
`

type GetPendingChaptersRow struct {
	Slug         string
	Language     string
	ChapterNum   string
	DictionaryID string
}

func (q *Queries) GetPendingChapters(ctx context.Context) ([]GetPendingChaptersRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingChapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingChaptersRow
	for rows.Next() {
		var i GetPendingChaptersRow
		if err := rows.Scan(
			&i.Slug,
			&i.Language,
			&i.ChapterNum,
			&i.DictionaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPendingChapters = `-- name: HasPendingChapters :one
SELECT COUNT(*) FROM manga_chapters WHERE slug=? AND uploaded=FALSE
`

func (q *Queries) HasPendingChapters(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasPendingChapters, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasUploadedChapters = `-- name: HasUploadedChapters :one
SELECT COUNT(*) FROM manga_chapters WHERE slug=? AND uploaded=TRUE
`

func (q *Queries) HasUploadedChapters(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasUploadedChapters, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listManga = `-- name: ListManga :many
WITH filtered AS (
    SELECT d.id AS dict_id, d.slug, d.state,
           COALESCE(m.title, d.title) AS title,
           COALESCE(m.status, '') AS status,
           COALESCE(m.description, '') AS description,
           COALESCE(NULLIF(m.cover_url, ''), NULLIF(d.cover_url, ''), '') AS cover_url,
           COALESCE(m.authors, '[]') AS authors,
           COALESCE(m.genres, '[]') AS genres,
           COALESCE(m.synced_at, d.created_at) AS synced_at
    FROM dictionary d
    LEFT JOIN manga m ON m.slug = d.slug
    WHERE (? = '' OR d.title LIKE CONCAT('%', ?, '%'))
      AND (? = '' OR d.state = ?)
      AND (? = '' OR m.status = ?)
      AND (? = FALSE OR d.state != 'unavailable')
),
counted AS (SELECT COUNT(*) AS total FROM filtered)
SELECT f.dict_id, f.slug, f.state, f.title, f.status, f.description,
       f.cover_url, f.authors, f.genres, f.synced_at,
       COALESCE((SELECT JSON_ARRAYAGG(language) FROM manga_langs WHERE slug = f.slug), '[]') AS languages,
       c.total
FROM filtered f, counted c
ORDER BY CASE WHEN ? = 'last_update' THEN f.synced_at END DESC,
         CASE WHEN ? != 'last_update' THEN f.title END ASC
LIMIT ? OFFSET ?
`

type ListMangaParams struct {
	Column1 interface{}
	CONCAT  interface{}
	Column3 interface{}
	State   string
	Column5 interface{}
	Status  string
	Column7 interface{}
	Column8 interface{}
	Column9 interface{}
	Limit   int32
	Offset  int32
}

type ListMangaRow struct {
	DictID      string
	Slug        string
	State       string
	Title       string
	Status      string
	Description string
	CoverUrl    interface{}
	Authors     json.RawMessage
	Genres      json.RawMessage
	SyncedAt    time.Time
	Languages   interface{}
	Total       int64
}

func (q *Queries) ListManga(ctx context.Context, arg ListMangaParams) ([]ListMangaRow, error) {
	rows, err := q.db.QueryContext(ctx, listManga,
		arg.Column1,
		arg.CONCAT,
		arg.Column3,
		arg.State,
		arg.Column5,
		arg.Status,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMangaRow
	for rows.Next() {
		var i ListMangaRow
		if err := rows.Scan(
			&i.DictID,
			&i.Slug,
			&i.State,
			&i.Title,
			&i.Status,
			&i.Description,
			&i.CoverUrl,
			&i.Authors,
			&i.Genres,
			&i.SyncedAt,
			&i.Languages,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChapterUploaded = `-- name: MarkChapterUploaded :exec
UPDATE manga_chapters SET uploaded=TRUE, uploaded_at=CURRENT_TIMESTAMP WHERE slug=? AND language=? AND chapter_num=?
`

type MarkChapterUploadedParams struct {
	Slug       string
	Language   string
	ChapterNum string
}

func (q *Queries) MarkChapterUploaded(ctx context.Context, arg MarkChapterUploadedParams) error {
	_, err := q.db.ExecContext(ctx, markChapterUploaded, arg.Slug, arg.Language, arg.ChapterNum)
	return err
}

const upsertChapter = `-- name: UpsertChapter :exec
INSERT INTO manga_chapters (slug, language, chapter_num, sort_key, page_count)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE sort_key=VALUES(sort_key), page_count=VALUES(page_count)
`

type UpsertChapterParams struct {
	Slug       string
	Language   string
	ChapterNum string
	SortKey    float64
	PageCount  int32
}

func (q *Queries) UpsertChapter(ctx context.Context, arg UpsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, upsertChapter,
		arg.Slug,
		arg.Language,
		arg.ChapterNum,
		arg.SortKey,
		arg.PageCount,
	)
	return err
}

const upsertLang = `-- name: UpsertLang :exec
INSERT INTO manga_langs (slug, language, available, downloaded)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE available=VALUES(available), downloaded=VALUES(downloaded)
`

type UpsertLangParams struct {
	Slug       string
	Language   string
	Available  int32
	Downloaded int32
}

func (q *Queries) UpsertLang(ctx context.Context, arg UpsertLangParams) error {
	_, err := q.db.ExecContext(ctx, upsertLang,
		arg.Slug,
		arg.Language,
		arg.Available,
		arg.Downloaded,
	)
	return err
}

const upsertManga = `-- name: UpsertManga :exec

INSERT INTO manga (uuid, slug, title, description, status, authors, genres, cover_url, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    title=VALUES(title), description=VALUES(description),
    status=VALUES(status), authors=VALUES(authors), genres=VALUES(genres),
    cover_url=CASE WHEN VALUES(cover_url) != '' THEN VALUES(cover_url) ELSE cover_url END,
    synced_at=CURRENT_TIMESTAMP
`

type UpsertMangaParams struct {
	Uuid        string
	Slug        string
	Title       string
	Description string
	Status      string
	Authors     json.RawMessage
	Genres      json.RawMessage
	CoverUrl    string
}

// catalog.sql: manga, manga_langs, manga_chapters, chapter_pages
func (q *Queries) UpsertManga(ctx context.Context, arg UpsertMangaParams) error {
	_, err := q.db.ExecContext(ctx, upsertManga,
		arg.Uuid,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Authors,
		arg.Genres,
		arg.CoverUrl,
	)
	return err
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO chapter_pages (slug, language, chapter_num, page_index, s3_url)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE s3_url=VALUES(s3_url)
`

type UpsertPageParams struct {
	Slug       string
	Language   string
	ChapterNum string
	PageIndex  int32
	S3Url      string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage,
		arg.Slug,
		arg.Language,
		arg.ChapterNum,
		arg.PageIndex,
		arg.S3Url,
	)
	return err
}
