// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapters.sql

package queries

import (
	"context"
)

const getChapterCountByLang = `-- name: GetChapterCountByLang :one
SELECT COUNT(*) FROM chapters WHERE manga_id = ? AND lang = ?
`

type GetChapterCountByLangParams struct {
	MangaID string
	Lang    string
}

func (q *Queries) GetChapterCountByLang(ctx context.Context, arg GetChapterCountByLangParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChapterCountByLang, arg.MangaID, arg.Lang)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChaptersByLang = `-- name: GetChaptersByLang :many
SELECT id, manga_id, name, chapter_order, lang, image_src
FROM chapters WHERE manga_id = ? AND lang = ? ORDER BY chapter_order ASC
`

type GetChaptersByLangParams struct {
	MangaID string
	Lang    string
}

type GetChaptersByLangRow struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
}

func (q *Queries) GetChaptersByLang(ctx context.Context, arg GetChaptersByLangParams) ([]GetChaptersByLangRow, error) {
	rows, err := q.db.QueryContext(ctx, getChaptersByLang, arg.MangaID, arg.Lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersByLangRow
	for rows.Next() {
		var i GetChaptersByLangRow
		if err := rows.Scan(
			&i.ID,
			&i.MangaID,
			&i.Name,
			&i.ChapterOrder,
			&i.Lang,
			&i.ImageSrc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChaptersByManga = `-- name: GetChaptersByManga :many
SELECT id, manga_id, name, chapter_order, lang, image_src
FROM chapters WHERE manga_id = ? ORDER BY lang, chapter_order ASC
`

type GetChaptersByMangaRow struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
}

func (q *Queries) GetChaptersByManga(ctx context.Context, mangaID string) ([]GetChaptersByMangaRow, error) {
	rows, err := q.db.QueryContext(ctx, getChaptersByManga, mangaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersByMangaRow
	for rows.Next() {
		var i GetChaptersByMangaRow
		if err := rows.Scan(
			&i.ID,
			&i.MangaID,
			&i.Name,
			&i.ChapterOrder,
			&i.Lang,
			&i.ImageSrc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChapterIngested = `-- name: IsChapterIngested :one
SELECT COUNT(*) FROM chapters WHERE manga_id = ? AND lang = ? AND chapter_order = ?
`

type IsChapterIngestedParams struct {
	MangaID      string
	Lang         string
	ChapterOrder int32
}

func (q *Queries) IsChapterIngested(ctx context.Context, arg IsChapterIngestedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isChapterIngested, arg.MangaID, arg.Lang, arg.ChapterOrder)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertChapter = `-- name: UpsertChapter :exec

INSERT INTO chapters (id, manga_id, name, chapter_order, lang, image_src)
VALUES (?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name=VALUES(name), chapter_order=VALUES(chapter_order),
    lang=VALUES(lang), image_src=VALUES(image_src)
`

type UpsertChapterParams struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
}

// chapters.sql: unified chapters table
func (q *Queries) UpsertChapter(ctx context.Context, arg UpsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, upsertChapter,
		arg.ID,
		arg.MangaID,
		arg.Name,
		arg.ChapterOrder,
		arg.Lang,
		arg.ImageSrc,
	)
	return err
}
