// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chapters.sql

package queries

import (
	"context"
	"encoding/json"
	"time"
)

const getChapterByID = `-- name: GetChapterByID :one
SELECT id, manga_id, name, chapter_order, lang, image_src, page_urls, page_count, updated_at
FROM chapters
WHERE id = ?
LIMIT 1
`

type GetChapterByIDRow struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
	PageUrls     json.RawMessage
	PageCount    int32
	UpdatedAt    time.Time
}

func (q *Queries) GetChapterByID(ctx context.Context, id string) (GetChapterByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChapterByID, id)
	var i GetChapterByIDRow
	err := row.Scan(
		&i.ID,
		&i.MangaID,
		&i.Name,
		&i.ChapterOrder,
		&i.Lang,
		&i.ImageSrc,
		&i.PageUrls,
		&i.PageCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getChapterCountByLang = `-- name: GetChapterCountByLang :one
SELECT COUNT(*) FROM chapters WHERE manga_id = ? AND lang = ?
`

type GetChapterCountByLangParams struct {
	MangaID string
	Lang    string
}

func (q *Queries) GetChapterCountByLang(ctx context.Context, arg GetChapterCountByLangParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChapterCountByLang, arg.MangaID, arg.Lang)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChapterUploaded = `-- name: GetChapterUploaded :one

SELECT image_src FROM chapters WHERE manga_id = ? AND lang = ? AND name = ? AND image_src IS NOT NULL AND image_src != '' LIMIT 1
`

type GetChapterUploadedParams struct {
	MangaID string
	Lang    string
	Name    string
}

// chapters.sql: unified chapters table
// Returns the image_src if the chapter has been uploaded (image_src IS NOT NULL AND image_src != ”), empty string otherwise.
func (q *Queries) GetChapterUploaded(ctx context.Context, arg GetChapterUploadedParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getChapterUploaded, arg.MangaID, arg.Lang, arg.Name)
	var image_src string
	err := row.Scan(&image_src)
	return image_src, err
}

const getChaptersByLang = `-- name: GetChaptersByLang :many
SELECT id, manga_id, name, chapter_order, lang, image_src
FROM chapters WHERE manga_id = ? AND lang = ? ORDER BY chapter_order ASC
`

type GetChaptersByLangParams struct {
	MangaID string
	Lang    string
}

type GetChaptersByLangRow struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
}

func (q *Queries) GetChaptersByLang(ctx context.Context, arg GetChaptersByLangParams) ([]GetChaptersByLangRow, error) {
	rows, err := q.db.QueryContext(ctx, getChaptersByLang, arg.MangaID, arg.Lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersByLangRow
	for rows.Next() {
		var i GetChaptersByLangRow
		if err := rows.Scan(
			&i.ID,
			&i.MangaID,
			&i.Name,
			&i.ChapterOrder,
			&i.Lang,
			&i.ImageSrc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChaptersByManga = `-- name: GetChaptersByManga :many
SELECT id, manga_id, name, chapter_order, lang, image_src
FROM chapters WHERE manga_id = ? ORDER BY lang, chapter_order ASC
`

type GetChaptersByMangaRow struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
}

func (q *Queries) GetChaptersByManga(ctx context.Context, mangaID string) ([]GetChaptersByMangaRow, error) {
	rows, err := q.db.QueryContext(ctx, getChaptersByManga, mangaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChaptersByMangaRow
	for rows.Next() {
		var i GetChaptersByMangaRow
		if err := rows.Scan(
			&i.ID,
			&i.MangaID,
			&i.Name,
			&i.ChapterOrder,
			&i.Lang,
			&i.ImageSrc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadedChaptersByLang = `-- name: GetUploadedChaptersByLang :many
SELECT id, manga_id, name, chapter_order, lang, image_src, page_urls, page_count, updated_at
FROM chapters WHERE manga_id = ? AND lang = ? AND image_src IS NOT NULL AND image_src != '' ORDER BY chapter_order ASC
`

type GetUploadedChaptersByLangParams struct {
	MangaID string
	Lang    string
}

type GetUploadedChaptersByLangRow struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
	PageUrls     json.RawMessage
	PageCount    int32
	UpdatedAt    time.Time
}

func (q *Queries) GetUploadedChaptersByLang(ctx context.Context, arg GetUploadedChaptersByLangParams) ([]GetUploadedChaptersByLangRow, error) {
	rows, err := q.db.QueryContext(ctx, getUploadedChaptersByLang, arg.MangaID, arg.Lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUploadedChaptersByLangRow
	for rows.Next() {
		var i GetUploadedChaptersByLangRow
		if err := rows.Scan(
			&i.ID,
			&i.MangaID,
			&i.Name,
			&i.ChapterOrder,
			&i.Lang,
			&i.ImageSrc,
			&i.PageUrls,
			&i.PageCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChapterIngested = `-- name: IsChapterIngested :one
SELECT COUNT(*) FROM chapters WHERE manga_id = ? AND lang = ? AND chapter_order = ?
`

type IsChapterIngestedParams struct {
	MangaID      string
	Lang         string
	ChapterOrder int32
}

func (q *Queries) IsChapterIngested(ctx context.Context, arg IsChapterIngestedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isChapterIngested, arg.MangaID, arg.Lang, arg.ChapterOrder)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertChapter = `-- name: UpsertChapter :exec
INSERT INTO chapters (id, manga_id, name, chapter_order, lang, image_src, page_urls, page_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    name=VALUES(name), chapter_order=VALUES(chapter_order),
    lang=VALUES(lang), image_src=VALUES(image_src),
    page_urls=VALUES(page_urls), page_count=VALUES(page_count)
`

type UpsertChapterParams struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
	PageUrls     json.RawMessage
	PageCount    int32
}

func (q *Queries) UpsertChapter(ctx context.Context, arg UpsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, upsertChapter,
		arg.ID,
		arg.MangaID,
		arg.Name,
		arg.ChapterOrder,
		arg.Lang,
		arg.ImageSrc,
		arg.PageUrls,
		arg.PageCount,
	)
	return err
}
