// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dictionary.sql

package queries

import (
	"context"
	"encoding/json"
	"time"
)

const getDictionary = `-- name: GetDictionary :one
SELECT id, slug, title, sources, source_stats, best_source, cover_url, updated_at, created_at
FROM dictionary WHERE id = ?
`

type GetDictionaryRow struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	CoverUrl    string
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

func (q *Queries) GetDictionary(ctx context.Context, id string) (GetDictionaryRow, error) {
	row := q.db.QueryRowContext(ctx, getDictionary, id)
	var i GetDictionaryRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Sources,
		&i.SourceStats,
		&i.BestSource,
		&i.CoverUrl,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDictionaryBySlug = `-- name: GetDictionaryBySlug :one
SELECT id, slug, title, sources, source_stats, best_source, cover_url, updated_at, created_at
FROM dictionary WHERE slug = ?
`

type GetDictionaryBySlugRow struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	CoverUrl    string
	UpdatedAt   time.Time
	CreatedAt   time.Time
}

func (q *Queries) GetDictionaryBySlug(ctx context.Context, slug string) (GetDictionaryBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getDictionaryBySlug, slug)
	var i GetDictionaryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Sources,
		&i.SourceStats,
		&i.BestSource,
		&i.CoverUrl,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDictionary = `-- name: ListDictionary :many
WITH filtered AS (
    SELECT id, slug, title, sources, source_stats, best_source, cover_url, updated_at, created_at
    FROM dictionary
    WHERE (? = '' OR title LIKE CONCAT('%', ?, '%'))
),
counted AS (SELECT COUNT(*) AS total FROM filtered)
SELECT f.id, f.slug, f.title, f.sources, f.source_stats, f.best_source, f.cover_url, f.updated_at, f.created_at, c.total
FROM filtered f, counted c
ORDER BY f.title
LIMIT ? OFFSET ?
`

type ListDictionaryParams struct {
	Column1 interface{}
	CONCAT  interface{}
	Limit   int32
	Offset  int32
}

type ListDictionaryRow struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	CoverUrl    string
	UpdatedAt   time.Time
	CreatedAt   time.Time
	Total       int64
}

func (q *Queries) ListDictionary(ctx context.Context, arg ListDictionaryParams) ([]ListDictionaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listDictionary,
		arg.Column1,
		arg.CONCAT,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDictionaryRow
	for rows.Next() {
		var i ListDictionaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Sources,
			&i.SourceStats,
			&i.BestSource,
			&i.CoverUrl,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDictionary = `-- name: UpsertDictionary :exec

INSERT INTO dictionary (id, slug, title, sources, source_stats, best_source, cover_url, updated_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
ON DUPLICATE KEY UPDATE
    title=VALUES(title),
    sources=JSON_MERGE_PATCH(dictionary.sources, VALUES(sources)),
    source_stats=CASE WHEN VALUES(source_stats) != '{}' THEN VALUES(source_stats) ELSE dictionary.source_stats END,
    best_source=CASE WHEN VALUES(best_source) != '{}' THEN VALUES(best_source) ELSE dictionary.best_source END,
    cover_url=CASE WHEN VALUES(cover_url) != '' THEN VALUES(cover_url) ELSE dictionary.cover_url END,
    updated_at=CURRENT_TIMESTAMP
`

type UpsertDictionaryParams struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	CoverUrl    string
	CreatedAt   time.Time
}

// dictionary.sql: dictionary table
func (q *Queries) UpsertDictionary(ctx context.Context, arg UpsertDictionaryParams) error {
	_, err := q.db.ExecContext(ctx, upsertDictionary,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Sources,
		arg.SourceStats,
		arg.BestSource,
		arg.CoverUrl,
		arg.CreatedAt,
	)
	return err
}
