// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dictionary.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getDictionary = `-- name: GetDictionary :one
SELECT id, slug, title, sources, source_stats, best_source, state, cover_url, refreshed_at, created_at
FROM dictionary WHERE id = ?
`

func (q *Queries) GetDictionary(ctx context.Context, id string) (Dictionary, error) {
	row := q.db.QueryRowContext(ctx, getDictionary, id)
	var i Dictionary
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Sources,
		&i.SourceStats,
		&i.BestSource,
		&i.State,
		&i.CoverUrl,
		&i.RefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDictionaryBySlug = `-- name: GetDictionaryBySlug :one
SELECT id, slug, title, sources, source_stats, best_source, state, cover_url, refreshed_at, created_at
FROM dictionary WHERE slug = ?
`

func (q *Queries) GetDictionaryBySlug(ctx context.Context, slug string) (Dictionary, error) {
	row := q.db.QueryRowContext(ctx, getDictionaryBySlug, slug)
	var i Dictionary
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Sources,
		&i.SourceStats,
		&i.BestSource,
		&i.State,
		&i.CoverUrl,
		&i.RefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDictionary = `-- name: ListDictionary :many
WITH filtered AS (
    SELECT id, slug, title, sources, source_stats, best_source, state, cover_url, refreshed_at, created_at
    FROM dictionary
    WHERE (? = '' OR title LIKE CONCAT('%', ?, '%'))
),
counted AS (SELECT COUNT(*) AS total FROM filtered)
SELECT f.id, f.slug, f.title, f.sources, f.source_stats, f.best_source, f.state, f.cover_url, f.refreshed_at, f.created_at, c.total
FROM filtered f, counted c
ORDER BY f.title
LIMIT ? OFFSET ?
`

type ListDictionaryParams struct {
	Column1 interface{}
	CONCAT  interface{}
	Limit   int32
	Offset  int32
}

type ListDictionaryRow struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	State       string
	CoverUrl    string
	RefreshedAt sql.NullTime
	CreatedAt   time.Time
	Total       int64
}

func (q *Queries) ListDictionary(ctx context.Context, arg ListDictionaryParams) ([]ListDictionaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listDictionary,
		arg.Column1,
		arg.CONCAT,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDictionaryRow
	for rows.Next() {
		var i ListDictionaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Sources,
			&i.SourceStats,
			&i.BestSource,
			&i.State,
			&i.CoverUrl,
			&i.RefreshedAt,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDictionaryState = `-- name: SetDictionaryState :exec
UPDATE dictionary SET state = ? WHERE id = ?
`

type SetDictionaryStateParams struct {
	State string
	ID    string
}

func (q *Queries) SetDictionaryState(ctx context.Context, arg SetDictionaryStateParams) error {
	_, err := q.db.ExecContext(ctx, setDictionaryState, arg.State, arg.ID)
	return err
}

const setDictionaryStateBySlug = `-- name: SetDictionaryStateBySlug :exec
UPDATE dictionary SET state = ? WHERE slug = ?
`

type SetDictionaryStateBySlugParams struct {
	State string
	Slug  string
}

func (q *Queries) SetDictionaryStateBySlug(ctx context.Context, arg SetDictionaryStateBySlugParams) error {
	_, err := q.db.ExecContext(ctx, setDictionaryStateBySlug, arg.State, arg.Slug)
	return err
}

const upsertDictionary = `-- name: UpsertDictionary :exec

INSERT INTO dictionary (id, slug, title, sources, source_stats, best_source, state, cover_url, refreshed_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    title=VALUES(title),
    sources=JSON_MERGE_PATCH(dictionary.sources, VALUES(sources)),
    source_stats=CASE WHEN VALUES(source_stats) != '{}' THEN VALUES(source_stats) ELSE dictionary.source_stats END,
    best_source=CASE WHEN VALUES(best_source) != '{}' THEN VALUES(best_source) ELSE dictionary.best_source END,
    state=CASE WHEN dictionary.state = 'available' THEN 'available' ELSE VALUES(state) END,
    cover_url=CASE WHEN VALUES(cover_url) != '' THEN VALUES(cover_url) ELSE dictionary.cover_url END,
    refreshed_at=CASE WHEN VALUES(refreshed_at) IS NOT NULL THEN VALUES(refreshed_at) ELSE dictionary.refreshed_at END
`

type UpsertDictionaryParams struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	State       string
	CoverUrl    string
	RefreshedAt sql.NullTime
	CreatedAt   time.Time
}

// dictionary.sql: dictionary table
func (q *Queries) UpsertDictionary(ctx context.Context, arg UpsertDictionaryParams) error {
	_, err := q.db.ExecContext(ctx, upsertDictionary,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Sources,
		arg.SourceStats,
		arg.BestSource,
		arg.State,
		arg.CoverUrl,
		arg.RefreshedAt,
		arg.CreatedAt,
	)
	return err
}
