// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest.sql

package queries

import (
	"context"
)

const getDownloadedByLang = `-- name: GetDownloadedByLang :many
SELECT language, COUNT(*) FROM ingest_chapters WHERE slug = ? GROUP BY language
`

type GetDownloadedByLangRow struct {
	Language string
	Count    int64
}

func (q *Queries) GetDownloadedByLang(ctx context.Context, slug string) ([]GetDownloadedByLangRow, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadedByLang, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDownloadedByLangRow
	for rows.Next() {
		var i GetDownloadedByLangRow
		if err := rows.Scan(&i.Language, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadedChaptersByLang = `-- name: GetDownloadedChaptersByLang :many
SELECT chapter_num FROM ingest_chapters WHERE slug = ? AND language = ? ORDER BY sort_key ASC
`

type GetDownloadedChaptersByLangParams struct {
	Slug     string
	Language string
}

func (q *Queries) GetDownloadedChaptersByLang(ctx context.Context, arg GetDownloadedChaptersByLangParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadedChaptersByLang, arg.Slug, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var chapter_num string
		if err := rows.Scan(&chapter_num); err != nil {
			return nil, err
		}
		items = append(items, chapter_num)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChapterDownloaded = `-- name: IsChapterDownloaded :one

SELECT COUNT(*) FROM ingest_chapters WHERE slug = ? AND language = ? AND chapter_num = ?
`

type IsChapterDownloadedParams struct {
	Slug       string
	Language   string
	ChapterNum string
}

// ingest.sql: ingest_chapters table
func (q *Queries) IsChapterDownloaded(ctx context.Context, arg IsChapterDownloadedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isChapterDownloaded, arg.Slug, arg.Language, arg.ChapterNum)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markChapterDownloaded = `-- name: MarkChapterDownloaded :exec
INSERT INTO ingest_chapters (slug, language, chapter_num, sort_key)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE sort_key=VALUES(sort_key)
`

type MarkChapterDownloadedParams struct {
	Slug       string
	Language   string
	ChapterNum string
	SortKey    float64
}

func (q *Queries) MarkChapterDownloaded(ctx context.Context, arg MarkChapterDownloadedParams) error {
	_, err := q.db.ExecContext(ctx, markChapterDownloaded,
		arg.Slug,
		arg.Language,
		arg.ChapterNum,
		arg.SortKey,
	)
	return err
}
