// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest.sql

package queries

import (
	"context"
)

const getDownloadedByLang = `-- name: GetDownloadedByLang :many

SELECT lang, COUNT(*) AS count FROM chapters WHERE manga_id = ? GROUP BY lang
`

type GetDownloadedByLangRow struct {
	Lang  string
	Count int64
}

// ingest.sql: chapter ingestion queries (replaced ingest_chapters)
// Chapter existence is now tracked via the chapters table.
// Returns language and count of chapters ingested per language for a manga.
func (q *Queries) GetDownloadedByLang(ctx context.Context, mangaID string) ([]GetDownloadedByLangRow, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadedByLang, mangaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDownloadedByLangRow
	for rows.Next() {
		var i GetDownloadedByLangRow
		if err := rows.Scan(&i.Lang, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadedChaptersByLang = `-- name: GetDownloadedChaptersByLang :many
SELECT chapter_order FROM chapters WHERE manga_id = ? AND lang = ? ORDER BY chapter_order ASC
`

type GetDownloadedChaptersByLangParams struct {
	MangaID string
	Lang    string
}

// Returns chapter_order values for chapters of a manga in a given language.
func (q *Queries) GetDownloadedChaptersByLang(ctx context.Context, arg GetDownloadedChaptersByLangParams) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadedChaptersByLang, arg.MangaID, arg.Lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var chapter_order int32
		if err := rows.Scan(&chapter_order); err != nil {
			return nil, err
		}
		items = append(items, chapter_order)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
