// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manga.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getMangaByDictionaryID = `-- name: GetMangaByDictionaryID :one
SELECT m.id, m.dictionary_id, m.title, m.description, m.status, m.authors, m.genres,
       m.cover_url, m.state, m.chapters_by_lang, m.updated_at, m.created_at
FROM manga m
WHERE m.dictionary_id = ?
`

func (q *Queries) GetMangaByDictionaryID(ctx context.Context, dictionaryID string) (Manga, error) {
	row := q.db.QueryRowContext(ctx, getMangaByDictionaryID, dictionaryID)
	var i Manga
	err := row.Scan(
		&i.ID,
		&i.DictionaryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Authors,
		&i.Genres,
		&i.CoverUrl,
		&i.State,
		&i.ChaptersByLang,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMangaByID = `-- name: GetMangaByID :one
SELECT m.id, m.dictionary_id, m.title, m.description, m.status, m.authors, m.genres,
       m.cover_url, m.state, m.chapters_by_lang, m.updated_at, m.created_at
FROM manga m
WHERE m.id = ?
`

func (q *Queries) GetMangaByID(ctx context.Context, id string) (Manga, error) {
	row := q.db.QueryRowContext(ctx, getMangaByID, id)
	var i Manga
	err := row.Scan(
		&i.ID,
		&i.DictionaryID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Authors,
		&i.Genres,
		&i.CoverUrl,
		&i.State,
		&i.ChaptersByLang,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listManga = `-- name: ListManga :many
SELECT m.id, m.dictionary_id, m.title, m.description, m.status, m.authors, m.genres,
       m.cover_url, m.state, m.chapters_by_lang, m.updated_at, m.created_at,
       COUNT(*) OVER () AS total
FROM manga m
WHERE (? = '' OR m.dictionary_id = ?)
  AND (? = '' OR m.title LIKE CONCAT('%', ?, '%') OR m.description LIKE CONCAT('%', ?, '%'))
  AND (? = '' OR m.state = ?)
ORDER BY
    CASE WHEN ? = 'title' AND ? = 'asc' THEN m.title END ASC,
    CASE WHEN ? = 'title' AND ? = 'desc' THEN m.title END DESC,
    CASE WHEN ? = 'updatedAt' AND ? = 'asc' THEN m.updated_at END ASC,
    CASE WHEN ? = 'updatedAt' AND ? = 'desc' THEN m.updated_at END DESC,
    CASE WHEN ? = 'createdAt' AND ? = 'asc' THEN m.created_at END ASC,
    CASE WHEN ? = 'createdAt' AND ? = 'desc' THEN m.created_at END DESC
LIMIT ? OFFSET ?
`

type ListMangaParams struct {
	Column1      interface{}
	DictionaryID string
	Column3      interface{}
	CONCAT       interface{}
	CONCAT_2     interface{}
	Column6      interface{}
	State        string
	Column8      interface{}
	Column9      interface{}
	Column10     interface{}
	Column11     interface{}
	Column12     interface{}
	Column13     interface{}
	Column14     interface{}
	Column15     interface{}
	Column16     interface{}
	Column17     interface{}
	Column18     interface{}
	Column19     interface{}
	Limit        int32
	Offset       int32
}

type ListMangaRow struct {
	ID             string
	DictionaryID   string
	Title          string
	Description    string
	Status         string
	Authors        json.RawMessage
	Genres         json.RawMessage
	CoverUrl       string
	State          string
	ChaptersByLang json.RawMessage
	UpdatedAt      sql.NullTime
	CreatedAt      sql.NullTime
	Total          interface{}
}

func (q *Queries) ListManga(ctx context.Context, arg ListMangaParams) ([]ListMangaRow, error) {
	rows, err := q.db.QueryContext(ctx, listManga,
		arg.Column1,
		arg.DictionaryID,
		arg.Column3,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.Column6,
		arg.State,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.Column17,
		arg.Column18,
		arg.Column19,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMangaRow
	for rows.Next() {
		var i ListMangaRow
		if err := rows.Scan(
			&i.ID,
			&i.DictionaryID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Authors,
			&i.Genres,
			&i.CoverUrl,
			&i.State,
			&i.ChaptersByLang,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertManga = `-- name: UpsertManga :exec

INSERT INTO manga (id, dictionary_id, title, description, status, authors, genres, cover_url, state, chapters_by_lang, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    title=VALUES(title),
    description=VALUES(description),
    status=VALUES(status),
    authors=VALUES(authors),
    genres=VALUES(genres),
    cover_url=CASE WHEN VALUES(cover_url) != '' THEN VALUES(cover_url) ELSE cover_url END,
    state=VALUES(state),
    chapters_by_lang=VALUES(chapters_by_lang),
    updated_at=CURRENT_TIMESTAMP
`

type UpsertMangaParams struct {
	ID             string
	DictionaryID   string
	Title          string
	Description    string
	Status         string
	Authors        json.RawMessage
	Genres         json.RawMessage
	CoverUrl       string
	State          string
	ChaptersByLang json.RawMessage
}

// manga.sql: manga table queries
func (q *Queries) UpsertManga(ctx context.Context, arg UpsertMangaParams) error {
	_, err := q.db.ExecContext(ctx, upsertManga,
		arg.ID,
		arg.DictionaryID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Authors,
		arg.Genres,
		arg.CoverUrl,
		arg.State,
		arg.ChaptersByLang,
	)
	return err
}
