// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Chapter struct {
	ID           string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	MangaID      string
}

type Dictionary struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	CoverUrl    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Manga struct {
	ID             string
	DictionaryID   string
	Title          string
	Description    string
	Status         string
	Authors        json.RawMessage
	Genres         json.RawMessage
	CoverUrl       string
	State          string
	ChaptersByLang json.RawMessage
	UpdatedAt      sql.NullTime
	CreatedAt      sql.NullTime
}
