// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Chapter struct {
	ID           string
	MangaID      string
	Name         string
	ChapterOrder int32
	Lang         string
	ImageSrc     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Dictionary struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	State       string
	CoverUrl    string
	RefreshedAt sql.NullTime
	CreatedAt   time.Time
}

type Manga struct {
	Slug        string
	Uuid        string
	Title       string
	Description string
	Status      string
	Authors     json.RawMessage
	Genres      json.RawMessage
	CoverUrl    string
	SyncedAt    time.Time
}

type Watchlist struct {
	Slug          string
	Title         string
	IntervalHours int32
	Period        string
	LastCheckedAt sql.NullTime
	Sources       json.RawMessage
	DictionaryID  sql.NullString
	ID            string
}
