// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ChapterPage struct {
	Slug       string
	Language   string
	ChapterNum string
	PageIndex  int32
	S3Url      string
}

type Dictionary struct {
	ID          string
	Slug        string
	Title       string
	Sources     json.RawMessage
	SourceStats json.RawMessage
	BestSource  json.RawMessage
	State       string
	CoverUrl    string
	RefreshedAt sql.NullTime
	CreatedAt   time.Time
}

type IngestChapter struct {
	Slug         string
	Language     string
	ChapterNum   string
	SortKey      float64
	DownloadedAt time.Time
}

type Manga struct {
	Slug        string
	Uuid        string
	Title       string
	Description string
	Status      string
	Authors     json.RawMessage
	Genres      json.RawMessage
	CoverUrl    string
	SyncedAt    time.Time
}

type MangaChapter struct {
	Slug       string
	Language   string
	ChapterNum string
	SortKey    float64
	PageCount  int32
	Uploaded   bool
	UploadedAt sql.NullTime
}

type MangaLang struct {
	Slug       string
	Language   string
	Available  int32
	Downloaded int32
}

type Watchlist struct {
	Slug          string
	Title         string
	IntervalHours int32
	Period        string
	LastCheckedAt sql.NullTime
	Sources       json.RawMessage
	DictionaryID  sql.NullString
	ID            string
}
