// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watchlist.sql

package queries

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addWatchlist = `-- name: AddWatchlist :exec

INSERT INTO watchlist (id, slug, title, sources, dictionary_id)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    title=VALUES(title), sources=VALUES(sources),
    dictionary_id=VALUES(dictionary_id)
`

type AddWatchlistParams struct {
	ID           string
	Slug         string
	Title        string
	Sources      json.RawMessage
	DictionaryID sql.NullString
}

// watchlist.sql: watchlist table
func (q *Queries) AddWatchlist(ctx context.Context, arg AddWatchlistParams) error {
	_, err := q.db.ExecContext(ctx, addWatchlist,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Sources,
		arg.DictionaryID,
	)
	return err
}

const listWatchlist = `-- name: ListWatchlist :many
SELECT COALESCE(id, ''), slug, title, sources, last_checked_at, COALESCE(dictionary_id, '') FROM watchlist ORDER BY slug
`

type ListWatchlistRow struct {
	ID            string
	Slug          string
	Title         string
	Sources       json.RawMessage
	LastCheckedAt sql.NullTime
	DictionaryID  string
}

func (q *Queries) ListWatchlist(ctx context.Context) ([]ListWatchlistRow, error) {
	rows, err := q.db.QueryContext(ctx, listWatchlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchlistRow
	for rows.Next() {
		var i ListWatchlistRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Sources,
			&i.LastCheckedAt,
			&i.DictionaryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWatchlist = `-- name: RemoveWatchlist :exec
DELETE FROM watchlist WHERE slug = ?
`

func (q *Queries) RemoveWatchlist(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, removeWatchlist, slug)
	return err
}

const updateLastChecked = `-- name: UpdateLastChecked :exec
UPDATE watchlist SET last_checked_at = ? WHERE slug = ?
`

type UpdateLastCheckedParams struct {
	LastCheckedAt sql.NullTime
	Slug          string
}

func (q *Queries) UpdateLastChecked(ctx context.Context, arg UpdateLastCheckedParams) error {
	_, err := q.db.ExecContext(ctx, updateLastChecked, arg.LastCheckedAt, arg.Slug)
	return err
}
