export { default as MangaPage } from './manga-page'
export { CoverImage } from './components/cover-image'
export { MangaDetailHeader } from './components/header'
export { StatusBadge, StateBadge, GenreBadge } from './components/badge'
export { LangTabs } from './components/lang-tabs'
export { LangProgressBar } from './components/progress-bar'
export { ChaptersPanel } from './components/chapters-panel'
export { ActionButtons } from './components/action-buttons'
